language: c

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - SETUP_CMD='test --coverage'
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='matplotlib scipy pyqt=5 Cython'
        - PIP_DEPENDENCIES='https://github.com/radio-astro-tools/spectral-cube/archive/master.zip qtpy six pytest-faulthandler pytest-qt'
        - CONDA_CHANNELS=astropy
        - SETUP_XVFB=True
        - PYTHON_VERSION=3.6
        - PYTEST_VERSION='<5'

matrix:
    include:
        - env: SETUP_CMD='egg_info'

        - env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.15 ASTROPY_VERSION=3.0
        - env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.16 ASTROPY_VERSION=3.1
        - env: PYTHON_VERSION=3.7 NUMPY_VERSION=1.16 ASTROPY_VERSION=3.2

        - env: PYTHON_VERSION=3.7 ASTROPY_VERSION=development

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - env: SETUP_CMD='build_sphinx -w'

        - env: PYTHON_VERSION=2.7 NUMPY_VERSION='' ASTROPY_VERSION='' CONDA_DEPENDENCIES='' PIP_DEPENDENCIES='astropy==2.0.16 scipy matplotlib https://github.com/radio-astro-tools/spectral-cube/archive/master.zip six'

before_install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - conda remove -y psutil --force || true
    - pip uninstall -y psutil || true

script:
    - python setup.py $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='pvextractor/tests/coveragerc'; fi
